<?php namespace App\Models;

/**
 * Eloquent class to describe the articles table
 *
 * automatically generated by ModelGenerator.php
 */
class Article extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'articles';

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('status', 'name', 'img', 'description', 'slug', 'meta_title', 'meta_keyword',
        'meta_description', 'deleted_at');

    public function usersCreatedBy()
    {
        return $this->belongsTo('App\Models\User', 'created_by_user_id', 'id');
    }

    public function usersUpdatedBy()
    {
        return $this->belongsTo('App\Models\User', 'updated_by_user_id', 'id');
    }
}
