<?php namespace App\Models;

/**
 * Eloquent class to describe the form_queries table
 *
 * automatically generated by ModelGenerator.php
 */
class FormQuery extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'form_queries';

    protected $fillable = array('name', 'email', 'phone_number', 'is_subscriber', 'comment', 'url');


}
