<?php namespace App\Models;

/**
 * Eloquent class to describe the medical_test_complexes table
 *
 * automatically generated by ModelGenerator.php
 */
class MedicalTestComplex extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'medical_test_complexes';

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('code', 'name', 'price', 'price_with_discount', 'is_promoted', 'deleted_at');

    public function usersCreatedBy()
    {
        return $this->belongsTo('App\Models\User', 'created_by_user_id', 'id');
    }

    public function usersUpdatedBy()
    {
        return $this->belongsTo('App\Models\User', 'updated_by_user_id', 'id');
    }

    public function medicalTestsInComplex()
    {
        return $this->hasMany('App\Models\MedicalTestsInComplex', 'medical_test_complex_id', 'id');
    }
}
