<?php namespace App\Models;

/**
 * Eloquent class to describe the medical_services table
 *
 * automatically generated by ModelGenerator.php
 */
class MedicalService extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'medical_services';

    public function getDates()
    {
        return array('deleted_at');
    }

    protected $fillable = array('name', 'price', 'price_with_discount', 'is_promoted', 'test_list', 'doctors_list',
        'period', 'deleted_at');

    public function medicalServiceGroups()
    {
        return $this->belongsTo('App\Models\MedicalServiceGroup', 'medical_service_group_id', 'id');
    }

    public function usersCreatedBy()
    {
        return $this->belongsTo('App\Models\User', 'created_by_user_id', 'id');
    }

    public function usersUpdatedBy()
    {
        return $this->belongsTo('App\Models\User', 'updated_by_user_id', 'id');
    }

    public function medicalServiceSubgroups()
    {
        return $this->belongsTo('App\Models\MedicalServiceSubgroup', 'subgroup_id', 'id');
    }
}
