<?php namespace App\Models;

/**
 * Eloquent class to describe the medical_service_groups table
 *
 * automatically generated by ModelGenerator.php
 */
class MedicalServiceGroup extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'medical_service_groups';

    protected $fillable = array('name', 'description', 'slug');

    public function medicalServices()
    {
        return $this->hasMany('App\Models\MedicalService', 'medical_service_group_id', 'id');
    }
}
