<?php namespace App\Models;

/**
 * Eloquent class to describe the orders table
 *
 * automatically generated by ModelGenerator.php
 */
class Order extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'orders';

    protected $fillable = array('user_name', 'email', 'phone_number', 'medical_test_id', 'price');

    public function testsInOrder()
    {
        return $this->hasMany('App\Models\TestsInOrder', 'order_id', 'id');
    }
}
