<?php namespace App;

/**
 * Eloquent class to describe the promotions table
 *
 * automatically generated by ModelGenerator.php
 */
class Promotion extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'promotions';

    public function getDates()
    {
        return array('started_date', 'end_date', 'deleted_at');
    }

    protected $fillable = array('started_date', 'end_date', 'status', 'name', 'description', 'created_by_user_id', 'img_preview',
        'img_banner', 'meta_title', 'meta_keyword', 'meta_description', 'deleted_at');

    public function usersCreatedBy()
    {
        return $this->belongsTo('App\Models\User', 'created_by_user_id', 'id');
    }

    public function usersUpdatedBy()
    {
        return $this->belongsTo('App\Models\User', 'updated_by_user_id', 'id');
    }
}
