<?php namespace App\Models;

/**
 * Eloquent class to describe the tests_in_order table
 *
 * automatically generated by ModelGenerator.php
 */
class TestsInOrder extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'tests_in_order';

    public $timestamps = false;

    protected $fillable = array('test_id', 'is_medical_test_complex');

    public function orders()
    {
        return $this->belongsTo('App\Models\Order', 'order_id', 'id');
    }
}
